### ISSUE TITLE
Handling MJPEG with warnings

### ISSUE THREAD

**Issue by tosiara** [Mr-Dave/motion#65] opened 2015-04-03 17:07 UTC
This was initially reported back in 2011:

http://www.lavrsen.dk/foswiki/bin/view/Motion/SupportQuestion2011x01x09x193606

The Logitech C910 camera simply does not work with motion in MJPEG format:
```
Corrupt JPEG data: 4 extraneous bytes before marker 0xd4
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 9 extraneous bytes before marker 0xd4
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 1 extraneous bytes before marker 0xd2
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 1 extraneous bytes before marker 0xd3
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 1 extraneous bytes before marker 0xd4
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 1 extraneous bytes before marker 0xd1
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 2 extraneous bytes before marker 0xd4
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 5 extraneous bytes before marker 0xd1
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 2 extraneous bytes before marker 0xd1
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
Corrupt JPEG data: 1 extraneous bytes before marker 0xd2
[1] [CRT] [VID] mjpegtoyuv420p: Corrupt image ... continue
```
To workaround the issue I changed this code:
```
diff --git a/video_common.c b/video_common.c
index 54569c6..f98154f 100644
--- a/video_common.c
+++ b/video_common.c
@@ -394,7 +394,7 @@ int mjpegtoyuv420p(unsigned char *map, unsigned char *cap_map, int width, int he
 
     if (ret == 1) {
         MOTION_LOG(CRT, TYPE_VIDEO, NO_ERRNO, "%s: Corrupt image ... continue");
-        ret = 2;
+        ret = 0;
     }
     return ret;
 }
```
Any other more sophisticated way to handle libjpeg warnings?

Mail list bump: http://sourceforge.net/p/motion/mailman/message/33700242/

**Comment by Mr-Dave** [comment] 2015-04-03 22:57
I believe that this might be addressed by the change in the Hackeron pull request in the Sackmotion fork.  I was reviewing that pull request to see how to get it into my fork.  It looks like it could not only address the corrupt JPG as well as address the FPS quality problems.  Probably want to address those separately though by having one change for the JPG and a different one for the FPS.

**Comment by tosiara** [comment] 2015-04-04 05:39
Good to hear!
Thanks

**Comment by Mr-Dave** [comment] 2015-08-30 03:20
I read this again and don't think that the code I was thinking of will resolve this issue.  The code I was looking at before was for handling netcams instead of webcams.  Do you have one of these cameras to use as a sample?  I think we'd need to get a few of the images and see whether they are still valid images if we were to ignore the extra bytes.

**Comment by tosiara** [comment] 2015-08-30 06:13
Yes, I still do have one and can get you some data soon

**Comment by Mr-Dave** [comment] 2015-08-30 17:18
I have just determined that one of my old cameras generates this warning so I do not need the sample image and I'll see if I can fix the root cause of the problem.

**Comment by Mr-Dave** [comment] 2015-08-31 23:55
Pushed a commit to unstable to enable this format.  The warnings from the jpeg routine are now being sent to the regular motion reporting mechanism so if desired, the user can see them via setting the logging at DBG.  The source of the problem is that the Logitech uses AVI1 format instead of JFIF and also occasionally fills the buffer with two SOI markers.  If a user has an option to use a different format from the camera, I'd recommend it.  Other formats should result in better performance and quality since there is less processing needed and even with this push, there is still the possibility of dropped frames.

**Comment by tosiara** [comment] 2015-09-01 11:28
FWIW, here are two sample frames from Logitech C910 camera

RAW: https://yadi.sk/d/_NQoc0xvioDDx
```
Format Video Capture:
	Width/Height  : 1920/1080
	Pixel Format  : 'YUYV'
	Field         : None
	Bytes per Line: 3840
	Size Image    : 4147200
	Colorspace    : SRGB
```
MJPEG: https://yadi.sk/d/dVIUajVEioDGD
```
Format Video Capture:
	Width/Height  : 1920/1080
	Pixel Format  : 'MJPG'
	Field         : None
	Bytes per Line: 0
	Size Image    : 4147200
	Colorspace    : SRGB
```

**Comment by Mr-Dave** [comment] 2015-09-21 17:23
Change was pushed to master.

**Closed by Mr-Dave** 2015-09-21 17:23 UTC
