### ISSUE TITLE
line 5283: syntax error near unexpected token `FFMPEG,'

### ISSUE THREAD

**Issue by mesmariusz** [Mr-Dave/motion#87] opened 2015-10-20 05:05 UTC
Could someone please help me?

./configure: line 5283: syntax error near unexpected token `FFMPEG,'
./configure: line 5283: `       PKG_CHECK_MODULES(FFMPEG, libavutil libavformat                                                                                                                      libavcodec libswscale, HAVE_FFMPEG=yes)'

log below:

root@LT310:~# apt-get install pkgconf
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności
Odczyt informacji o stanie... Gotowe
Zostaną zainstalowane następujące NOWE pakiety:
  pkgconf
0 aktualizowanych, 1 nowo instalowanych, 0 usuwanych i 99 nieaktualizowanych.
Konieczne pobranie 28,2 kB archiwów.
Po tej operacji zostanie dodatkowo użyte 130 kB miejsca na dysku.
Pobieranie:1 http://ftp.pl.debian.org/debian/ jessie/main pkgconf i386 0.9.7-1 [                                                                                                  28,2 kB]
Pobrano 28,2 kB w 5s (5451 B/s)
Wybieranie wcześniej niewybranego pakietu pkgconf.
(Odczytywanie bazy danych ... 109271 plików i katalogów obecnie zainstalowanych.)
Przygotowywanie do rozpakowania pakietu .../pkgconf_0.9.7-1_i386.deb ...
Dodawanie "ominięcie /usr/bin/pkg-config do /usr/bin/pkg-config.real przez pkgconf"
Dodawanie "ominięcie /usr/share/aclocal/pkg.m4 do /usr/share/aclocal/pkg.real.m4                                                                                                                      przez pkgconf"
Dodawanie "ominięcie /usr/share/man/man1/pkg-config.1.gz do /usr/share/man/man1/                                                                                                                     pkg-config.real.1.gz przez pkgconf"
Dodawanie "ominięcie /usr/share/pkg-config-crosswrapper do /usr/share/pkg-config                                                                                                                     -crosswrapper.real przez pkgconf"
Rozpakowywanie pakietu pkgconf (0.9.7-1) ...
Przetwarzanie wyzwalaczy pakietu man-db (2.7.0.2-5)...
Konfigurowanie pakietu pkgconf (0.9.7-1) ...

root@LT310:~# ls
Dokumenty  motion  Obrazy   Publiczny  Szablony  x264
ffmpeg     Muzyka  Pobrane  Pulpit     Wideo

root@LT310:~# cd motion

root@LT310:~/motion# ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking for Darwin... no
checking for *BSD... no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking threads... yes
checking for sdl... no
checking for libjpeg-turbo... skipping
checking for libjpeg-mmx... skipping
checking for jpeg_set_defaults in -ljpeg... yes
./configure: line 5283: syntax error near unexpected token `FFMPEG,'
./configure: line 5283: `       PKG_CHECK_MODULES(FFMPEG, libavutil libavformat                                                                                                                      libavcodec libswscale, HAVE_FFMPEG=yes)'
root@LT310:~/motion#

**Comment by Mr-Dave** [comment] 2015-10-20 13:52
This is a duplicate of your post on your other list.

**Closed by Mr-Dave** 2015-10-20 13:52 UTC

**Comment by mesmariusz** [comment] 2015-10-20 14:19
This is not a duplicate...  Just look on the log. pkgconf is installed and
this didn't solve my issue.

http://pastebin.com/nJvG8hKt
20 paź 2015 15:52 "Mr-Dave" <notifications@github.com> napisał(a):
